### ISSUE TITLE
Quantifier restrictions

### ISSUE THREAD

**Issue by rzach** [rzach/forallx-yyc#57]
Something my students are persistently confused about is when a quantifier has to be restricted and when it doesn't have to be.  E.g., in a mixed domain you want to symbolize "Someone is blah". Do you have to restrict the \exists to people or not? When do you have to restrict? Can you symbolize "someone" without restricting to people? There should perhaps be some sort of discussion on this in the book.

E.g., I received the following by email:

> A question about Sec 24.4. For the following example:  Someone is a dog owner.
This symbolization is given: ∃y∃x(D(x) ∧O(y,x)) But since the domain includes both animals and human beings, shouldn't '∃y' be restricted? I.e., Something like ∃y∃x(D(x) ∧ Person(y) ∧ O(y,x)).

This is well taken, but the symbolization key doesn't even include a predicate for "person". Figure out what to do here.

**Comment by nicolewyatt** [comment]
I don't think this example exhibits the problem you describe. Someone is  restricted to humans, but rather excludes inanimates (there's a lot of interesting pragmatic stuff surrounding when we use something for animates, but this is beside the point here).

Of course most people would assume in this case that dog owners must be human, but the sentence would not standardly be taken to literally say that. Perhaps dogs own other dogs in some alternate possibility.

More generally there is unlikely to be an easy solution to this problem, since part of the process of logical education is training students to exclude a large amount of what is ordinarily communicated based on background knowledge from their understanding of what a sentence says in order to symbolize it.

--NMW

--
Nicole Wyatt PhD,
Associate Professor and Head
Department of Philosophy
University of Calgary

Book an appointment: calendly.com/nicole-wyatt<https://calendly.com/nicole-wyatt>

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Richard Zach ***@***.***>
Sent: Saturday, July 16, 2022 4:45:54 PM
To: rzach/forallx-yyc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rzach/forallx-yyc] Quantifier restrictions (Issue #57)

[△EXTERNAL]



Something my students are persistently confused about is when a quantifier has to be restricted and when it doesn't have to be. E.g., in a mixed domain you want to symbolize "Someone is blah". Do you have to restrict the \exists to people or not? When do you have to restrict? Can you symbolize "someone" without restricting to people? There should perhaps be some sort of discussion on this in the book.

E.g., I received the following by email:

A question about Sec 24.4. For the following example: Someone is a dog owner.
This symbolization is given: ∃y∃x(D(x) ∧O(y,x)) But since the domain includes both animals and human beings, shouldn't '∃y' be restricted? I.e., Something like ∃y∃x(D(x) ∧ Person(y) ∧ O(y,x)).

This is well taken, but the symbolization key doesn't even include a predicate for "person". Figure out what to do here.

**Comment by rzach** [comment]
Did you mean "Someone is NOT restricted to humans". If ∃y∃x(D(x) ∧O(y,x)) is an acceptable symbolization of "Someone owns a dog" then ∀y∃x(D(x) ∧O(y,x)) would have to be a correct symbolization of "Everyone owns a dog". That seems wrong to me, as it's false whenever some dogs aren't dog owners.

As a pedagogical question (and not one about semantics vs pragmatics) it seems to me that whether or not quantifiers should have a restriction in symbolization should be uniform (ie either both "everyone" and "someone" must be restricted to people, or neither should) and should track truth value (and it seems to me that "everyone owns a dog" is true whenever all the people in the domain are dog owners).

**Comment by nicolewyatt** [comment]
Yes, I meant NOT restricted to humans — I kept trying to edit this for clarity and obviously the result was suboptimal!

I do think ∀y∃x(D(x) ∧O(y,x)) is a correct symbolization of "Everyone owns a dog" in the interpretation you described. Of course in almost all cases in which we say that English sentence pragmatic would be contextually restricting the range of the quantifier in some way. This would go well beyond pragmatically excluding dogs from the range of course, since it is vanishingly unlikely that we would even mean it to range over every human.

As to the pedagogical point, I agree that we should be consistent. I think that consistently directing them to treat the difference between everyone/someone and everything/something as irrelevant to formalization is the way to go. My view is that any other approach will create ambiguities.

If we tell students, for example, that everyone/someone are equivalent to every human/some human, then we will get the wrong formalization for a sentence like:

Everyone on DS9 has been to Quark's.

But if we tell them that everyone/someone are equivalent to every person/some person, then a student who thinks that at least some non-human animals are persons (a not unheard-of position) will be inclined to symbolize differently than a student who disagrees.

In the end I don't think that symbolization of natural language can be captured in hard and fast rules -- it's very much a matter of context and the aims of the formalization. But consistency in a text book is of course to be desired. -- NMW

Please know that my working hours may not be your working hours: do not feel obliged to respond outside of your normal schedule.

--

Dr. Nicole Wyatt (she/her)
Associate Professor and Head
Department of Philosophy
University of Calgary

President, Society for Exact Philosophy

***@***.***

Book an appointment at: https://calendly.com/nicole-wyatt


Living and working within the traditional territories of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikuni, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations. The City of Calgary is also home to Metis Nation of Alberta, Region III.
________________________________

**Comment by rzach** [comment]
Can't we get around the DS9 issue by restricting to persons instead of humans? Ie unless the domain is just people, we always add a "person" predicate that restricts everyone/someone/noone, just like we would add time and place predicates that restrict "sometime" and "everywhere"?

I mean if ∀y∃x(D(x) ∧O(y,x)) is a correct symbolization of "Everyone owns a dog" then it looks like you cannot say anything true using that English sentence in an interpretation where there are toys (or other things that cannot own dogs). That seems odd.

**Comment by nicolewyatt** [comment]
Restriction to persons is better -- i.e. closer to how we use some/everyone -- than restriction to humans. But it creates some other issues, namely that the truth-value of `Everyone is a dog owner' translated as ∀y∃x(P(x) → (D(x) ∧O(y,x))) now hinges of whether dogs are persons or not (if they are, and as in the actual world dogs don't own dogs, its false, if they aren't, it's true).

Maybe this doesn't matter in this context? - NMW


--

Dr. Nicole Wyatt (she/her)
Associate Professor and Head
Department of Philosophy
University of Calgary

President, Society for Exact Philosophy

***@***.***

Book an appointment at: https://calendly.com/nicole-wyatt


Living and working within the traditional territories of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikuni, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations. The City of Calgary is also home to Metis Nation of Alberta, Region III.

________________________________

**Comment by rzach** [comment]
I would say that that issue isn't the job of a logician (or semanticist) to deal with. "Everyone owns a dog" should be symbolized the same way as "For every person there is a dog they own". If you wanted to say something true but some dogs are persons and they don't own dogs, then you should have said something else, e.g., "every human owns a dog" (and that would be symbolized differently). I think that's a better position to be in as far as the textbook is concerned.  The alternative position is pretty bad: we would have to say that you can't symbolize "Everyone owns a dog" and make it come out true in the situation described where dogs exist and don't own any dogs.

**Comment by rzach** [comment]
Fixed (I hope) in commit 3a3f5ab

**Comment by nicolewyatt** [comment]
Works for me! - N

--

Dr. Nicole Wyatt (she/her)
Associate Professor and Head
Department of Philosophy
University of Calgary

President, Society for Exact Philosophy

***@***.***

Book an appointment at: https://calendly.com/nicole-wyatt


Living and working within the traditional territories of the Blackfoot and the people of the Treaty 7 region in Southern Alberta, which includes the Siksika, the Piikuni, the Kainai, the Tsuut’ina and the Stoney Nakoda First Nations. The City of Calgary is also home to Metis Nation of Alberta, Region III.

________________________________
